// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0Jqn7RbVGA0WD-_qamdtXqJZRToQW0M',
    appId: '1:48987067227:web:81d9239ae03df33f59807e',
    messagingSenderId: '48987067227',
    projectId: 'fih-test-c8ebd',
    authDomain: 'fih-test-c8ebd.firebaseapp.com',
    storageBucket: 'fih-test-c8ebd.appspot.com',
    measurementId: 'G-G238FRK0K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSZvF8-fKSet_41aFDQkQYYDyNRvW3d4',
    appId: '1:48987067227:android:592fd9d13bdc4b5159807e',
    messagingSenderId: '48987067227',
    projectId: 'fih-test-c8ebd',
    storageBucket: 'fih-test-c8ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt95ErR2zXe7hK8BULMY6J8mw9KIyanGg',
    appId: '1:48987067227:ios:0b6882bc14ecd9af59807e',
    messagingSenderId: '48987067227',
    projectId: 'fih-test-c8ebd',
    storageBucket: 'fih-test-c8ebd.appspot.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt95ErR2zXe7hK8BULMY6J8mw9KIyanGg',
    appId: '1:48987067227:ios:0b6882bc14ecd9af59807e',
    messagingSenderId: '48987067227',
    projectId: 'fih-test-c8ebd',
    storageBucket: 'fih-test-c8ebd.appspot.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0Jqn7RbVGA0WD-_qamdtXqJZRToQW0M',
    appId: '1:48987067227:web:84366b636442b4e459807e',
    messagingSenderId: '48987067227',
    projectId: 'fih-test-c8ebd',
    authDomain: 'fih-test-c8ebd.firebaseapp.com',
    storageBucket: 'fih-test-c8ebd.appspot.com',
    measurementId: 'G-0MVQL21DCF',
  );

}