// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD34kPzVEurweXJFrn5PTdqUmHFS_T6_U',
    appId: '1:982533764740:web:19b5f88b3872aac970f4d1',
    messagingSenderId: '982533764740',
    projectId: 'fih-test-ce7f0',
    authDomain: 'fih-test-ce7f0.firebaseapp.com',
    storageBucket: 'fih-test-ce7f0.appspot.com',
    measurementId: 'G-4WRH2W28QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--sxrC6FCCL7UyCIEgQwOIXAq2s_NJL8',
    appId: '1:982533764740:android:67fe61549b4caab070f4d1',
    messagingSenderId: '982533764740',
    projectId: 'fih-test-ce7f0',
    storageBucket: 'fih-test-ce7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6EZpG5_idusCmFaS2IqcH0yxRjtOC0YY',
    appId: '1:982533764740:ios:fa32679d1d6e8c8b70f4d1',
    messagingSenderId: '982533764740',
    projectId: 'fih-test-ce7f0',
    storageBucket: 'fih-test-ce7f0.appspot.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6EZpG5_idusCmFaS2IqcH0yxRjtOC0YY',
    appId: '1:982533764740:ios:fa32679d1d6e8c8b70f4d1',
    messagingSenderId: '982533764740',
    projectId: 'fih-test-ce7f0',
    storageBucket: 'fih-test-ce7f0.appspot.com',
    iosBundleId: 'com.example.math',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD34kPzVEurweXJFrn5PTdqUmHFS_T6_U',
    appId: '1:982533764740:web:c9ecd645f5c8fc1570f4d1',
    messagingSenderId: '982533764740',
    projectId: 'fih-test-ce7f0',
    authDomain: 'fih-test-ce7f0.firebaseapp.com',
    storageBucket: 'fih-test-ce7f0.appspot.com',
    measurementId: 'G-NMLWQT260R',
  );

}